### ISSUE TITLE
Devo utilizar Prism com Xamarin Forms?

### ISSUE THREAD

**Issue by ericleber-santos** [MonkeyNights/beer-trade#10]
Fiz um projeto com Xamarin Forms pra Android e publiquei, ele recebe/envia dados e fotos para uma API Rest em PHP(não fiz a API). 

Agora estou utilizando Prism em projetos de estudo, é muito  cedo?

**Comment by felipebaltazar** [comment]
nunca é cedo ou tarde demais pra estudar prism! ❤️

**Comment by angelobelchior** [comment]
@eriindie eu penso que a principal questão é a senioridade. Você acaba de colocar um belo item no seu portifólio de desenvolvimento. 
Com o passar do tempo você vai amadurecendo, e ganhando mais experiência :)
