### ISSUE TITLE
Feedback sobre a primeira live

### ISSUE THREAD

**Issue by wsrzx** [MonkeyNights/beer-trade#12]
- O que você achou da primeira Live? 
- Em que podemos melhorar?
- O que você faria diferente?

**Comment by l0gaw** [comment]
1 - Muito boa essa abordagem. Gostei demais!
2 - Sem sugestão por enquanto.
3 - Sem sugestão por enquanto.

**Comment by felipebaltazar** [comment]
Achei do caralh**! ja aprendi muita coisa

**Comment by Anderkops** [comment]
Sensacional, bem dinamica

**Comment by rodrigoratan** [comment]
achei perfeito vcs terem focado na infraestrutura do projeto pois deixar pra fazer isso depois dá azar. no proximo foquem no framework imho

**Comment by CognumDeveloper** [comment]
Muito boa mesmo... Parece trabalho cotidiano... Sem sugestões por enquanto...

**Comment by BrunoRuiz** [comment]
O que achou da primeira live?
 - Muito bacana, gostei de ter iniciado a partir da estruturação dos fontes e repositório e da automatização dos builds!

O que podemos melhorar?
 - Acredito que está bacana neste formato! Manda bala que no decorrer das próximas a gente consegue pensar em algo se tiver pra melhorar!

O que vc faria de diferente?
 - NADA! 👏🏻

**Comment by jaiconM** [comment]
Ficou show esse formato. Participei das outras 3 maratonas e esse formato de Live ficou show também.

**Comment by eduardocordova21** [comment]
O que você achou da primeira Live?
   Muito boooooa!   

Em que podemos melhorar?
   Alguns momentos o áudio cortava, mas nada grave. 

O que você faria diferente?
   Compartilharia as suas redes sociais, para podermos acompanhar seus projetos e planos para o futuro 
   do Xamarin haha

**Comment by Fabricio-Pereira** [comment]
Nesse formato de live, ficou muito top, já aprendi muito hoje.

**Comment by kainaalmeida** [comment]
O que você achou da primeira Live?
- Muito boa e didática. Já aprendi muita coisa apenas nessa primeira live.
Em que podemos melhorar?
- Sem sugestões no momento.
O que você faria diferente?
- Sem sugestões no momento.

**Comment by TonhaoSemAcento** [comment]
Muito melhor o formato de live, com bate papo, poder tirar as dúvidas. Sensacional!

**Comment by mapsouza** [comment]
1) Ótimo! Neste formato não tem como não aprender!
2) Fazer alguns testes aí de como melhorar a imagem do Mac! Ficou tudo muito pequeno!
3) Sem sugestões

**Comment by brunosalmeida** [comment]
- O que você achou da primeira Live?
   Muito boa a iniciativa! O formato de live é bem mais dinâmico!. 
- Em que podemos melhorar?
  Seria interessante ter uma pauta com os objetivos a serem alcançados em cada live.

**Comment by Tmaturano** [comment]
1 - Excelente, esse AppCenter ai é fenomenal, ainda mais com 240horas de build gratuítos e sem informar cartão de crédito 👍  O format em Live, já tiramos as dúvidas e vemos as dificuldades ali na hora agrega muito, obrigado galera.
2 - Sem sugestões no momento
3 - Sem sugestões no momento

**Comment by ejastre** [comment]
Seria interessante termos a experiencia do VS 2019 para Windows, pois acredito que esse sera o ambiente da grande maioria. Assim tambem podemos comparar as melhorias em relacao ao VS2017. Valeu!

**Comment by diegolobo** [comment]
1 - Monstruosa, quem teve essa ideia? Meus parabéns!!!  
2 - Sem sugestões no momento
3 - Sem sugestões no momento

**Comment by haroldjose30** [comment]
1 -  Muito interessante, bem diferente de um curso que queria ou nao ja existe milhares por ai...  Essa forma interativa é o principal diferencial...  vamos ver como vao indo se houver alguma ideia ou consideraçao que possa auxiliar, vou postar aqui!
2 - Sem sugestao no momento
3 - Sem sugestao no momento

**Comment by graffitiMSX** [comment]
Não pude assistir e nem poderei na próxima terça, por compromissos pessoais, mas a partir da 3a assistirei assiduamente!

1. O que você achou da primeira Live?

Estou acompanhando o vídeo agora no YT e adorando, de tanto ver e rever vários tópicos já passei o dia inteiro aqui!

Aprendendo muito em termos de processos, simplesmente fantástico, era o que eu estava precisando!

2. Em que podemos melhorar?

Acho que está muito bom, nada como reunir um Dream Team pra fazer algo nesse porte!

3. O que você faria diferente?

Por enquanto tá tudo indo muito bem, sigam em frente! Parabéns!

**Comment by felipefrg** [comment]
O que você achou da primeira Live?
Achei o formato bem interessante, diferente e proveitoso.

Em que podemos melhorar?
Ficou dificil a visualização, boa parte o William esquecia de dar zoom e sua voz saía mais baixo que as dos demais, nas proximas se puder calibrar o microfone acredito que ficaria melhor.

O que você faria diferente?
Por enquanto tá tudo indo muito bem, parabéns a todos!
