### ISSUE TITLE
Criei a solução no VS2019. Template diferente do VS for MAC.

### ISSUE THREAD

**Issue by pliniobrunelli** [MonkeyNights/beer-trade#14]
No Windows, criei a solução no VS2019, mas não apareceu a opção de adicionar o UITest Project. Precisei adicionar manualmente. Embora, no fim das contas ficou tudo igual, tem como adicionar o projeto de testes no momento da criação da solução?

![image](https://user-images.githubusercontent.com/27024755/56630051-3bd33a80-6626-11e9-8c31-c003b060350a.png)

**Comment by jorgecensi** [comment]
Por padrao, somente no VS for mac, mas voce consegue criar um template personalizado usando um template ja existente.

segue o link:

 https://docs.microsoft.com/en-us/visualstudio/ide/how-to-create-multi-project-templates?view=vs-2019
