### ISSUE TITLE
Vai rolar testes no Projeto? Se sim, quais?

### ISSUE THREAD

**Issue by ejastre** [MonkeyNights/beer-trade#16]
Tipo Unit Tests, UI Tests, AppCenter Tests, etc

**Comment by wsrzx** [comment]
O que você sugere @ejastre?

**Comment by ejastre** [comment]
Ja que estamos usando o AppCenter sugiro criar tb os testes de UI / Launch e tb testes Unitarios para as ViewModels, se essa for a abordagem correta de testes para XF. Valeu

**Comment by akamud** [comment]
Por mim vai. Todos que fizerem sentido.

**Comment by wsrzx** [comment]
Rolou na terceira live :)
