### ISSUE TITLE
Firebase, Azure...etc, o que usar? e o mais Barato?

### ISSUE THREAD

**Issue by Jean-Alves** [MonkeyNights/beer-trade#18]
Tenho uma idéia de app, que alem do app, criarei 1 admin para gerenciar o app,
Sendo assim, qual usar? e o custo ?

**Comment by angelobelchior** [comment]
@Jean-Alves essas questões dependem muito do seu APP. Cada plataforma tem suas peculiaridades.
Sobre o que usar, você precisara cruzar as features do seu APP com as features que cada plataforma disponibiliza.
Sobre o custo, tendo em mente as features que você vai usar, no próprio site do serviço você obterá essas informações.

**Comment by haroldjose30** [comment]
@Jean-Alves não sei se ajuda, mas pra projetos pessoais e gastar pouco com isso, eu estou usando o www.linode.com durante o periodo inicial de testes pra hospedar o Backend em linux com asp.net core e mySql... por apenas 5$ mensal... mas só pra o periodo de testes porque por esse valor a maquina é bem fraquinha... depois pretendo colocar no Azure ou pagar um plano melhor, porem esse servidor nao fica no brasil entao provavel que eu mude mesmo pro Azure.
