### ISSUE TITLE
DisplayAlert no ViewModel

### ISSUE THREAD

**Issue by gabrielborchardt** [MonkeyNights/beer-trade#19]
O Melhor caminho é utilizar Messageria?

"MessagingCenter.Subscribe"

**Comment by akamud** [comment]
Não precisa ser. Você pode criar uma camada de abstração pra que seja possível disparar direto da ViewModel. Semelhante ao que o Prism [disponibiliza](https://prismlibrary.github.io/docs/xamarin-forms/Page-Dialog-Service.html).

Assim sua tela continua desacoplada da *implementação* da View.
