### ISSUE TITLE
Feedback sobre a segunda live

### ISSUE THREAD

**Issue by angelobelchior** [MonkeyNights/beer-trade#21]
O que você achou da segunda Live?
Em que podemos melhorar?
O que você faria diferente?

**Comment by jorgecensi** [comment]
O que você achou da segunda Live?
Distribuir app na apple store é uma coisa que nunca fiz, então a live foi importante para aprender como se faz de uma maneira mais rápida .

Em que podemos melhorar?
Enquanto uma pessoa apresenta, os outros integrantes poderiam atuar como alguém  que está  aprendendo também  e fazer perguntas básicas mesmo, reforçando o conhecimento de quem já o tem e explicando pra quem esta iniciando.

O que você faria diferente?
Ao final de cada live definir o assunto da próxima live mesmo que na próxima acabe tendo mais conteúdo do que previsto.

Parabéns galera, continuem com o entusiasmo.

**Comment by Oguima** [comment]
Show, muito interessante a abordagem de resolver build e publicações no início do projeto; creio que a maneira que eu começava era, sair codando até alguma necessidade de publicação surgir, e perder muito tempo para resolver depois... Ficar brigando com devs por quebra de certificados, e desesperos quando o dev que builda sai de férias ... Muito obrigado por essa nova visão pra mim :D ... O Mud explicou muito bem, e teve problemas AO VIVO; todos resolvidos rapidamente, e até hoje só os Monkey Nights conseguem resolver problemas ao vivo, parabéns sou muito #FÃ. O que poderia melhorar ... O Angelo parar de dar spoilers :P , mas como já devo ter visto todos vídeos do canal dele, ta liberado ... sou #FÃ ... ps só deu pra ver hoje, que a prioridade em feriados e fins de semana, é do filho :D

**Comment by brunosalmeida** [comment]
O que você achou da segunda Live?
Muito bom fazer este setup inicial. É uma coisa que deveria ser prioridade logo na sprint 0 em qualquer projeto. O AppCenter é muito prático pra isto. A dinâmica do grupo ficou boa. Foi ditto no começo quais os pontos seriam abordados na live. 
Em que podemos melhorar?
Poderiam mencionar outras plataformas que fazer algo semalhante que o appcenter faz.
