### ISSUE TITLE
Feedback sobre a terceira live!

### ISSUE THREAD

**Issue by wsrzx** [MonkeyNights/beer-trade#25]
- O que você achou da segunda Live?
- Em que podemos melhorar?
- O que você faria diferente?

**Comment by TonhaoSemAcento** [comment]
Curti a parte de testes. Não uso principal por nunca saber o que testar. O exemplo de property foi bem massa, principalmente a parte de tentar achar o menor valor que dá erro.

**Comment by mapsouza** [comment]
Show! Primeiro conteúdo que vejo bem legal sobre testes.
Ainda está complicado as imagens de tela. Talvez seja o caso de remover as imagens dos participantes da parte de baixo

**Comment by brunosalmeida** [comment]
O que você achou da segunda Live?
O testes são sempre importantes. E como disseram o mais importante que testar é saber o que testar. 
Em que podemos melhorar?
Seria legal se esses conceitos importantes como teste, CI/CD fosse mostrado dentro do escopo do projeto proposto (como foi feito com CI e CD no AppCenter). 
O que você faria diferente?
Como foi dito na live anterior que seria escolhido qual framework seria utilizado, já faria a instalação do pacotes nugets e a configuração incial do projeto e iniciaria a construção da primeira viewmodel e aplicaria os conceitos de teste explicado pelo Will dentro do scopo do projeto.

**Comment by Tmaturano** [comment]
As dicas sobre gerar o Code Coverage sem a necessidade de ter o VS Enterprise para mim foram muito valiosas, eu desconhecia e já me ajudou em um projeto que fiz um refactor incluindo testes de unidade e o cliente queria saber a cobertura, como eu não tenho o VS Enterprise, fiquei devendo isso para ele, mas agora eu já consigo medir esta cobertura, muito obrigado!

**Comment by simix-felipebaltazar** [comment]
Não consegui acompanhar ao vivo, mas vi logo em seguida!!
Uma coisa que notei (fora do tópico de testes) é uma visão que eu tenho de alguns colegas. Em frequentes casos preciso explicar o funcionamento do `Async` `Await` aqui na empresa, acho que vale uma talk sobre especificamente esses caras (obviamente não precisa ser exclusivamente vinculado ao beer-trade).
Quanto ao assunto principal, TA MUITO FODA!

**Comment by felipefrg** [comment]
Achei excelente, essa live cobriu assuntos pouco abordados.
Poderia fazer um hands-on de testes de UI e de Integração.
