### ISSUE TITLE
Sobre o async Task 

### ISSUE THREAD

**Issue by joseBarreto** [MonkeyNights/beer-trade#26]
Olá gente,
na ultima live, sobre os testes, vocês recomendaram não utilizar async void. 
Porém, para métodos que estão ligados na view, e eles tem que ser async, usar
public async task OnMethod retorna erro.

"Unhandled Exception:
Xamarin.Forms.Xaml.XamlParseException: Position 98:36. Method OnMethod does not have the correct signature"

**Comment by akamud** [comment]
Todos métodos que hoje tem a assinatura com `void` e terão chamadas `async` dentro vão ter que ser `async void` mesmo. Isso é bem comum em métodos nativos que fazemos override pois eles não têm essa assinatura com retorno de `Task`. Mas tá tudo bem, essa é outra exceção além de event handlers.

O ponto é, sempre que possível: evite `async void` para não ter os problemas que comentamos de engolir exceptions e de não conseguir "delegar" o `await` somente quando necessário. Nem sempre isso vai ser possível.
