### ISSUE TITLE
Projeto com mais de 100 estrelas

### ISSUE THREAD

**Issue by simix-felipebaltazar** [MonkeyNights/beer-trade#28]
O projeto conseguiu mais de 100 estrelas, cadê o cabelo azul do @willbuildapps  e do @angelobelchior  ?
🤡 
#YoutuberFeelings

**Comment by simix-felipebaltazar** [comment]
corrigindo... era a barba 😅

**Comment by wsrzx** [comment]
hahaha, para hoje não vai dar kkk...
