### ISSUE TITLE
😀 Como abrir uma issue?

### ISSUE THREAD

**Issue by wsrzx** [MonkeyNights/beer-trade#3]
Acesse https://github.com/MonkeyNights/beer-trade/issues

**Comment by oberdanf** [comment]
Oi

**Comment by angelobelchior** [comment]
Que legal, agora eu posso colocar minhas dúvidas aqui :)

**Comment by WilliamSantosSilva** [comment]
Teste

**Comment by haroldjose30** [comment]
é aberto a todos comentarem na issue? vamos ver...

**Comment by TonhaoSemAcento** [comment]
MA OEEEEE

**Comment by hernanicamargo** [comment]
eeeheheheeh

**Comment by dionmauricio** [comment]
Bem mais pratico (apenas para teste)

**Comment by digao13** [comment]
Salve

**Comment by felipebaltazar** [comment]
#LiveDoMagoo

**Comment by edenilsonfe** [comment]
Hey

**Comment by luizhj** [comment]
aguardando o ditado do Ângelo

**Comment by matheus1899** [comment]
Aeeee

**Comment by BrunoRuiz** [comment]
Saudações corinthianas #VaiCurintia 👊🏻😎

**Comment by rodrigoratan** [comment]
PALMEIRAS PRIMEIRO CAMPEAO MUNDIAL DE CLUBES

**Comment by wsrzx** [comment]
@rodrigoratan Obrigado por acabar com a thread :)

**Comment by felipebaltazar** [comment]
não deixa a issue morrer!!

**Comment by WilliamSantosSilva** [comment]
não deixe a issue acabar .....

**Comment by andersondealmeidasp** [comment]
Direto de Carapicuíba para o mundo!

**Comment by rodrigoratan** [comment]
pow @willbuildapps justo vc deu thumbs down? rs
