### ISSUE TITLE
Link all assemblies

### ISSUE THREAD

**Issue by jorgecensi** [MonkeyNights/beer-trade#35]
Como faço pra descobrir qual assembly esta sendo removido pelo linker sendo que consigo rodar o App mas ele nāo exibe nada na pagina?

segue o repo no qual estou tentando ativar o link all: https://github.com/jorgecensi/BolaoJovemNerd

**Comment by simix-felipebaltazar** [comment]
Você pode tentar achar oque foi removido através de ferramentas de comparação de assemblies
Se você estiver no Windows, pode utilizar o [BitDiffer ](https://github.com/bitdiffer/bitdiffer) que o @akamud citou na [ultima live](https://youtu.be/uKo1YN9VJx8) e também falou nos videos da maratona [xamarin avançada](https://www.youtube.com/watch?v=oGDw4_huJeM&list=PLB1hpnUGshUIusyBsQ42cmlYRra4eaKqa&index=24), nessa inclusive ele também faz um passo a passo verificando os assemblies

**Comment by akamud** [comment]
É exatamente o que acontecia na nossa live @jorgecensi, você pode ver nosso raciocínio e como o @simix-felipebaltazar bem citou, eu já mostrei como usar algumas ferramentas que nos ajudam também.

O BitDiffer roda no Unix também, só não tem GUI bonitinho. Ele gera um report HTML que é bem menos legível, mas pode ajudar mesmo assim.
