### ISSUE TITLE
Sugestão de extensão Vs Mac

### ISSUE THREAD

**Issue by mapsouza** [MonkeyNights/beer-trade#36]
Na criação do App deu trabalho para atualizar todos os pacotes NuGet pelo Vs Mac? 
Essa extensão habilita a opção Manage NuGet Packages como no Vs 2019.

https://github.com/mrward/monodevelop-nuget-extensions

**Comment by oberdanf** [comment]
Versão do add-in para VS4Mac 2019
https://github.com/mrward/monodevelop-addins/tree/gh-pages/8.0
