### ISSUE TITLE
Linker All Assemblies com 20mb

### ISSUE THREAD

**Issue by cassionandi** [MonkeyNights/beer-trade#44]

**Comment by wsrzx** [comment]
Cassio, nós tinhamos salvado sua pergunta para responder ao vivo na live de hoje :/

**Comment by cassionandi** [comment]
> Cassio, nós tinhamos salvado sua pergunta para responder ao vivo na live de hoje :/

oh god! Mals William, é que achei que estava no lugar errado aqui.

**Comment by cassionandi** [comment]
Mas basicamente era pra saber o que diabos fiz de errado pra não consegui chegar nos 14mb com o mesmo exato projeto (e linker.xml), mesmo com apenas um ABI pro Android. 

Refiz toda a instalação do VS4Mac pra ver se tinha algo faltando ou desatualizado, continua tudo igual.

**Comment by cassionandi** [comment]
Talvez tenha relação rapazes
https://github.com/xamarin/xamarin-android/issues/3454

**Comment by akamud** [comment]
Bem provável que seja essa issue sim @cassionandi. Tem um fix no preview já, se você tiver acesso a uma instalação com Preview pode validar.

**Comment by cassionandi** [comment]
> Bem provável que seja essa issue sim @cassionandi. Tem um fix no preview já, se você tiver acesso a uma instalação com Preview pode validar.

Agora sim! 15.3mb apenas o ABI x86 habilitado!

**Comment by wsrzx** [comment]
Show de bola @cassionandi eu vou fechar a issue, se tiver algum problema pode abrir novamente.
