### ISSUE TITLE
O que eu preciso ler para companhar as lives?

### ISSUE THREAD

**Issue by vagnerdearaujo** [MonkeyNights/beer-trade#5]
Fiquei perdido com o início do projeto e está difícil acompanhar.
Preciso me conectar ao App Center poder buildar o projeto?

**Comment by akamud** [comment]
Oi Vagner, no começo falamos de várias coisas bem comuns quando estamos iniciando projetos e que são essenciais pra conseguirmos tocar esse projeto de forma que ele fique organizado.

* Usamos o Git com um [gitignore](https://git-scm.com/docs/gitignore) próprio pro nosso tipo de projeto, gerado pelo [gitignore.io](https://gitignore.io/)
* Falamos de ter um [editorconfig](https://editorconfig.org/) pra que o code style do código fique uniforme e garantido de maneira automatizada pelas IDEs/Editores
* Utilizamos o plano grátis do VS AppCenter pra fazer o build, e possivelmente utilizaremos no futuro pra Crash/Analytics e Distribuição. Fica a seu critério utilizar ele para o seu projeto, ele não é obrigatório mas traz vantagens de práticas ágeis como [Continuous Integration](https://en.wikipedia.org/wiki/Continuous_integration) e [Continuous Deploy](https://en.wikipedia.org/wiki/Continuous_delivery) e altamente recomendado.

**Comment by akamud** [comment]
Outro ponto importante, pegando o projeto inicial daqui, vocês não precisam se preocupar com mais nada desses primeiros pontos, eles vão estar no repositório e vocês vão estar tirando proveitos dela. Asim vocês podem ir pegando aos poucos ;)

**Comment by MarcosAC** [comment]
Poderiam fazer uma live  explicando a usar o AppCenter. Se já não fizeram. :D

**Comment by akamud** [comment]
@MarcosAC na maratona 2018 a [Letticia Nicoli](https://twitter.com/letticianicoli) fez um módulo abordando todos os pontos do App Center. Dá uma olhada [aqui](https://www.youtube.com/watch?v=Tq5iwVweawM&list=PLB1hpnUGshUIusyBsQ42cmlYRra4eaKqa&index=27&t=0s).
