### ISSUE TITLE
Eu clonei o projeto e está apresentando erro no VS2019

### ISSUE THREAD

**Issue by vagnerdearaujo** [MonkeyNights/beer-trade#8]
Sei que o projeto ainda não tem nada funcional, mas o erro abaixo é normal?
Estou com Windows10 e VS2019 versão 16.0.1

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1201	Project BeerTrade.iOS is not compatible with net461 (.NETFramework,Version=v4.6.1) / win-x86. Project BeerTrade.iOS supports: xamarinios10 (Xamarin.iOS,Version=v1.0)	BeerTrade.UITests	C:\Users\vagne\Source\Repos\beer-trade\src\BeerTrade\BeerTrade.UITests\BeerTrade.UITests.csproj	1

**Comment by dionmauricio** [comment]
Essa documentação acende uma luz sobre esse erro
https://docs.microsoft.com/pt-br/nuget/reference/errors-and-warnings/nu1201

**Comment by wsrzx** [comment]
@vagnerdearaujo Tente instalar a versão v4.6.1 utilizando o https://dotnet.microsoft.com/download/dotnet-framework/net461

**Comment by WilliamSantosSilva** [comment]
@willbuildapps só instalando e resolve ? O meu tá no mesmo.

Severity	Code	Description	Project	File	Line	Suppression State
Error	NU1201	Project BeerTrade.iOS is not compatible with net461 (.NETFramework,Version=v4.6.1) / win-x86. Project BeerTrade.iOS supports: xamarinios10 (Xamarin.iOS,Version=v1.0)	BeerTrade.UITests	C:\Projects\Cursos\Meetups\Xamarin\MonkeyNights\src\BeerTrade\BeerTrade.UITests\BeerTrade.UITests.csproj	1

**Comment by felipebaltazar** [comment]
Descarregando o projeto `BeerTrade.UITests.csproj` da pra executar o build

**Comment by SamirMMBr** [comment]
No meu caso ainda estou no VS2019 Preview 16.0.0 não deu tempo de instalar a versão final.
Passos:

1. Abrir o VS, selecione Clonar do GitHub e informe a URL deste projeto.
2. Abrir a Solution BeerTrade
3. Clicar com botão direito na Solution e selecionar Gerenciador de Configurações
4. Desmarcar (  ) Compilar iOS, UITests

![image](https://user-images.githubusercontent.com/19651573/56630046-3544c300-6626-11e9-8871-69f3c7f8fee8.png)

**Comment by rodrigoratan** [comment]
Aqui to com VS2019 recem instalado, com o workload de mobile completo, ultimos SDKs e da isso:

![image](https://user-images.githubusercontent.com/964066/56677845-bd16e580-6697-11e9-9fad-2120e3fa4faa.png)

**Comment by wsrzx** [comment]
@WilliamSantosSilva não entendi, você fez a instalação e não resolveu é isso? 

> @willbuildapps só instalando e resolve ? O meu tá no mesmo.
> 
> Severity	Code	Description	Project	File	Line	Suppression State
> Error	NU1201	Project BeerTrade.iOS is not compatible with net461 (.NETFramework,Version=v4.6.1) / win-x86. Project BeerTrade.iOS supports: xamarinios10 (Xamarin.iOS,Version=v1.0)	BeerTrade.UITests	C:\Projects\Cursos\Meetups\Xamarin\MonkeyNights\src\BeerTrade\BeerTrade.UITests\BeerTrade.UITests.csproj	1

**Comment by wsrzx** [comment]
@rodrigoratan envia um print dos seus workloads e SDK's instalados, plzs (tu pode pegar isso no visual studio installer)

> Aqui to com VS2019 recem instalado, com o workload de mobile completo, ultimos SDKs e da isso:
> 
> ![image](https://user-images.githubusercontent.com/964066/56677845-bd16e580-6697-11e9-9fad-2120e3fa4faa.png)

**Comment by demysla** [comment]
> @vagnerdearaujo Tente instalar a versão v4.6.1 utilizando o https://dotnet.microsoft.com/download/dotnet-framework/net461

Não consegui instalar esta versão porque já tenho a v4.7 instalada.
Estou tendo o mesmo erro.
