### ISSUE TITLE
Qual framework MVVM utilizar no projeto?

### ISSUE THREAD

**Issue by wsrzx** [MonkeyNights/beer-trade#9]
Por favor vote em cada opção utilizando reactions 👍🏼

**Comment by wsrzx** [comment]
Prism https://prismlibrary.github.io/

**Comment by wsrzx** [comment]
FreshMVVM https://github.com/rid00z/FreshMvvm

**Comment by rodrigoratan** [comment]
MVVM Light - http://www.mvvmlight.net/ e http://jesseliberty.com/2018/01/03/mvvm-light-and-xamarin-forms/

**Comment by wsrzx** [comment]
Fazer na mão!

**Comment by wsrzx** [comment]
MvvvmCross https://www.mvvmcross.com/

**Comment by wsrzx** [comment]
Reactiveui https://reactiveui.net

**Comment by wsrzx** [comment]
Vai ser Prism.
